// ============================================================
// TEST.JS
// Student Mock Test
// GitHub Pages
// No Firebase
// No Server
// ============================================================
import {
    decodeTest,
    tokenFromUrl,
    esc,
    fmt
} from './common.js';
// ============================================================
// VARIABLES
// ============================================================
let test = null;
let idx = 0;
let answers = {};
let seconds = 0;
let timerId = null;
let startTime = 0;
let studentName = '';
let rollNo = '';
// ============================================================
// INITIALIZE
// ============================================================
function init() {
    try {
        const token = tokenFromUrl();
        // ----------------------------------------------------
        // NO TOKEN
        // ----------------------------------------------------
        if (!token) {
            loadMsg.textContent =
                'This page needs a test link generated by the teacher.';
            return;
        }
        // ----------------------------------------------------
        // DECODE TEST
        //
        // IMPORTANT:
        // decodeTest() is SYNCHRONOUS.
        //
        // DO NOT USE await.
        // ----------------------------------------------------
        test = decodeTest(token);
        // ----------------------------------------------------
        // INVALID TEST
        // ----------------------------------------------------
        if (
            !test ||
            !Array.isArray(test.questions) ||
            test.questions.length === 0
        ) {
            loadMsg.textContent =
                'The test link is invalid or contains no questions.';
            return;
        }
        // ----------------------------------------------------
        // VALIDATE MINUTES
        // ----------------------------------------------------
        test.minutes = Math.max(
            1,
            Number(test.minutes) || 30
        );
        // ----------------------------------------------------
        // SHOW START SCREEN
        // ----------------------------------------------------
        loading.classList.add('hidden');
        start.classList.remove('hidden');
        // ----------------------------------------------------
        // TEST INFORMATION
        // ----------------------------------------------------
        testTitle.textContent =
            test.title || 'Mock Test';
        startTitle.textContent =
            test.title || 'Mock Test';
        testInfo.textContent =
            test.questions.length +
            ' questions • ' +
            test.minutes +
            ' minutes';
    } catch (error) {
        console.error(
            'Test loading error:',
            error
        );
        loadMsg.textContent =
            'Unable to load the test: ' +
            (error.message || String(error));
    }
}
// ============================================================
// START BUTTON
// ============================================================
startBtn.onclick = begin;
// ============================================================
// BEGIN TEST
// ============================================================
function begin() {
    studentName =
        document
            .getElementById('studentName')
            .value
            .trim();
    rollNo =
        document
            .getElementById('rollNo')
            .value
            .trim();
    // --------------------------------------------------------
    // NAME REQUIRED
    // --------------------------------------------------------
    if (!studentName) {
        alert(
            'Please enter your name.'
        );
        document
            .getElementById('studentName')
            .focus();
        return;
    }
    // --------------------------------------------------------
    // RESET TEST
    // --------------------------------------------------------
    idx = 0;
    answers = {};
    seconds =
        test.minutes * 60;
    startTime =
        Date.now();
    // --------------------------------------------------------
    // SHOW EXAM
    // --------------------------------------------------------
    start.classList.add('hidden');
    exam.classList.remove('hidden');
    // --------------------------------------------------------
    // RESET TIMER
    // --------------------------------------------------------
    clearInterval(timerId);
    timer.classList.remove('urgent');
    // --------------------------------------------------------
    // RENDER FIRST QUESTION
    // --------------------------------------------------------
    render();
    // --------------------------------------------------------
    // START TIMER
    // --------------------------------------------------------
    timerId =
        setInterval(
            tick,
            1000
        );
    updateTimer();
}
// ============================================================
// TIMER
// ============================================================
function updateTimer() {
    if (seconds < 0) {
        seconds = 0;
    }
    timer.textContent =
        fmt(seconds);
    if (seconds <= 60) {
        timer.classList.add(
            'urgent'
        );
    }
}
// ============================================================
// TIMER TICK
// ============================================================
function tick() {
    seconds--;
    updateTimer();
    // --------------------------------------------------------
    // TIME FINISHED
    // --------------------------------------------------------
    if (seconds <= 0) {
        clearInterval(timerId);
        finish(true);
    }
}
// ============================================================
// RENDER QUESTION
// ============================================================
function render() {
    const q =
        test.questions[idx];
    if (!q) {
        return;
    }
    // --------------------------------------------------------
    // PROGRESS
    // --------------------------------------------------------
    progress.textContent =
        'Question ' +
        (idx + 1) +
        ' of ' +
        test.questions.length;
    // --------------------------------------------------------
    // ANSWERED COUNT
    // --------------------------------------------------------
    answeredCount.textContent =
        Object.keys(answers).length +
        ' answered';
    // --------------------------------------------------------
    // QUESTION
    // --------------------------------------------------------
    question.innerHTML =
        '<h2>' +
        esc(q.question) +
        '</h2>' +
        Object.entries(
            q.options || {}
        )
        .map(
            function ([key, value]) {
                const selected =
                    answers[q.id] === key
                        ? ' selected'
                        : '';
                return (
                    '<button ' +
                    'type="button" ' +
                    'class="option' +
                    selected +
                    '" ' +
                    'data-option="' +
                    esc(key) +
                    '">' +
                    '<b>' +
                    esc(key) +
                    ')</b> ' +
                    esc(value) +
                    '</button>'
                );
            }
        )
        .join('');
    // --------------------------------------------------------
    // OPTION CLICK
    // --------------------------------------------------------
    question
        .querySelectorAll('.option')
        .forEach(
            function (button) {
                button.onclick =
                    function () {
                        answers[q.id] =
                            button.dataset.option;
                        render();
                    };
            }
        );
    // --------------------------------------------------------
    // PREVIOUS BUTTON
    // --------------------------------------------------------
    prevBtn.disabled =
        idx === 0;
    // --------------------------------------------------------
    // NEXT BUTTON
    // --------------------------------------------------------
    nextBtn.disabled =
        idx ===
        test.questions.length - 1;
    // --------------------------------------------------------
    // QUESTION NUMBERS
    // --------------------------------------------------------
    numbers.innerHTML =
        test.questions
            .map(
                function (item, n) {
                    const answered =
                        answers[item.id]
                            ? 'answered '
                            : '';
                    const current =
                        n === idx
                            ? 'current'
                            : '';
                    return (
                        '<button ' +
                        'type="button" ' +
                        'class="qnum ' +
                        answered +
                        current +
                        '">' +
                        (n + 1) +
                        '</button>'
                    );
                }
            )
            .join('');
    // --------------------------------------------------------
    // QUESTION NUMBER CLICK
    // --------------------------------------------------------
    numbers
        .querySelectorAll('.qnum')
        .forEach(
            function (button, n) {
                button.onclick =
                    function () {
                        idx = n;
                        render();
                    };
            }
        );
}
// ============================================================
// PREVIOUS
// ============================================================
prevBtn.onclick =
    function () {
        if (idx > 0) {
            idx--;
            render();
        }
    };
// ============================================================
// NEXT
// ============================================================
nextBtn.onclick =
    function () {
        if (
            idx <
            test.questions.length - 1
        ) {
            idx++;
            render();
        }
    };
// ============================================================
// SUBMIT
// ============================================================
submitBtn.onclick =
    function () {
        finish(false);
    };
// ============================================================
// FINISH TEST
// ============================================================
function finish(auto) {
    // --------------------------------------------------------
    // SAFETY CHECK
    // --------------------------------------------------------
    if (
        !test ||
        !Array.isArray(test.questions)
    ) {
        return;
    }
    // --------------------------------------------------------
    // MANUAL SUBMIT CONFIRMATION
    // --------------------------------------------------------
    if (!auto) {
        const confirmed =
            confirm(
                'Are you sure you want to submit the test?'
            );
        if (!confirmed) {
            return;
        }
    }
    // --------------------------------------------------------
    // STOP TIMER
    // --------------------------------------------------------
    clearInterval(timerId);
    // --------------------------------------------------------
    // CALCULATE CORRECT
    // --------------------------------------------------------
    let correct = 0;
    test.questions.forEach(
        function (q) {
            if (
                answers[q.id] ===
                q.answer
            ) {
                correct++;
            }
        }
    );
    // --------------------------------------------------------
    // ATTEMPTED
    // --------------------------------------------------------
    const attempted =
        Object.keys(
            answers
        ).length;
    // --------------------------------------------------------
    // WRONG
    // --------------------------------------------------------
    let wrong = 0;
    Object.keys(
        answers
    ).forEach(
        function (id) {
            const q =
                test.questions.find(
                    function (item) {
                        return (
                            String(item.id) ===
                            String(id)
                        );
                    }
                );
            if (
                q &&
                answers[id] !==
                q.answer
            ) {
                wrong++;
            }
        }
    );
    // --------------------------------------------------------
    // UNANSWERED
    // --------------------------------------------------------
    const unanswered =
        test.questions.length -
        attempted;
    // --------------------------------------------------------
    // PERCENTAGE
    // --------------------------------------------------------
    const percent =
        test.questions.length > 0
            ? Math.round(
                (
                    correct /
                    test.questions.length
                ) * 100
            )
            : 0;
    // --------------------------------------------------------
    // TIME TAKEN
    // --------------------------------------------------------
    const timeTaken =
        Math.round(
            (
                Date.now() -
                startTime
            ) / 1000
        );
    // --------------------------------------------------------
    // RESULT
    // --------------------------------------------------------
    const result = {
        title:
            test.title || 'Mock Test',
        name:
            studentName,
        roll:
            rollNo,
        total:
            test.questions.length,
        attempted:
            attempted,
        correct:
            correct,
        wrong:
            wrong,
        unanswered:
            unanswered,
        percent:
            percent,
        timeTaken:
            timeTaken,
        answers:
            answers,
        questions:
            test.questions,
        autoSubmitted:
            auto
    };
    // --------------------------------------------------------
    // SAVE RESULT
    // --------------------------------------------------------
    try {
        sessionStorage.setItem(
            'mockResult',
            JSON.stringify(result)
        );
    } catch (error) {
        console.error(
            'Result save error:',
            error
        );
        alert(
            'Unable to save your result.'
        );
        return;
    }
    // --------------------------------------------------------
    // OPEN RESULT PAGE
    // --------------------------------------------------------
    window.location.href =
        'result.html';
}
// ============================================================
// INITIALIZE
// ============================================================
init();
