// ============================================================
// TEST.JS
// Student Mock Test
// GitHub Pages
// No Firebase
// No Server
// ============================================================
import {
    decodeTest,
    tokenFromUrl,
    esc,
    fmt
} from './common.js';
// ============================================================
// VARIABLES
// ============================================================
let test = null;
let idx = 0;
let answers = {};
let seconds = 0;
let timerId = null;
let startTime = 0;
let studentName = '';
let rollNo = '';
let finished = false;
// ============================================================
// DOM ELEMENTS
// ============================================================
const loadMsg =
    document.getElementById('loadMsg');
const loading =
    document.getElementById('loading');
const start =
    document.getElementById('start');
const exam =
    document.getElementById('exam');
const testTitle =
    document.getElementById('testTitle');
const startTitle =
    document.getElementById('startTitle');
const testInfo =
    document.getElementById('testInfo');
const startBtn =
    document.getElementById('startBtn');
const timer =
    document.getElementById('timer');
const progress =
    document.getElementById('progress');
const answeredCount =
    document.getElementById('answeredCount');
const question =
    document.getElementById('question');
const prevBtn =
    document.getElementById('prevBtn');
const nextBtn =
    document.getElementById('nextBtn');
const submitBtn =
    document.getElementById('submitBtn');
const numbers =
    document.getElementById('numbers');
// ============================================================
// CHECK REQUIRED HTML ELEMENTS
// ============================================================
function checkElements() {
    const required = {
        loadMsg,
        loading,
        start,
        exam,
        testTitle,
        startTitle,
        testInfo,
        startBtn,
        timer,
        progress,
        answeredCount,
        question,
        prevBtn,
        nextBtn,
        submitBtn,
        numbers
    };
    const missing =
        Object.keys(required)
            .filter(
                key => !required[key]
            );
    if (missing.length > 0) {
        console.error(
            'Missing HTML elements:',
            missing
        );
        return false;
    }
    return true;
}
// ============================================================
// INITIALIZE
// ============================================================
function init() {
    if (!checkElements()) {
        alert(
            'Test page error: Some required HTML elements are missing. Check test.html IDs.'
        );
        return;
    }
    try {
        // ----------------------------------------------------
        // GET TOKEN
        // ----------------------------------------------------
        const token =
            tokenFromUrl();
        // ----------------------------------------------------
        // NO TOKEN
        // ----------------------------------------------------
        if (!token) {
            loadMsg.textContent =
                'This page needs a test link generated by the teacher.';
            return;
        }
        // ----------------------------------------------------
        // DECODE TEST
        // ----------------------------------------------------
        test =
            decodeTest(token);
        // ----------------------------------------------------
        // INVALID TEST
        // ----------------------------------------------------
        if (
            !test ||
            !Array.isArray(
                test.questions
            ) ||
            test.questions.length === 0
        ) {
            loadMsg.textContent =
                'The test link is invalid or contains no questions.';
            return;
        }
        // ----------------------------------------------------
        // DEFAULT TITLE
        // ----------------------------------------------------
        if (
            !test.title ||
            String(test.title).trim() === ''
        ) {
            test.title =
                'Mock Test';
        }
        // ----------------------------------------------------
        // VALIDATE MINUTES
        // ----------------------------------------------------
        test.minutes =
            Math.max(
                1,
                Number(
                    test.minutes
                ) || 30
            );
        // ----------------------------------------------------
        // SHOW START SCREEN
        // ----------------------------------------------------
        loading.classList.add(
            'hidden'
        );
        start.classList.remove(
            'hidden'
        );
        // ----------------------------------------------------
        // TEST INFORMATION
        // ----------------------------------------------------
        testTitle.textContent =
            test.title;
        startTitle.textContent =
            test.title;
        testInfo.textContent =
            test.questions.length +
            ' questions • ' +
            test.minutes +
            ' minutes';
    } catch (error) {
        console.error(
            'Test loading error:',
            error
        );
        loadMsg.textContent =
            'Unable to load the test: ' +
            (
                error.message ||
                String(error)
            );
    }
}
// ============================================================
// START BUTTON
// ============================================================
startBtn.onclick =
    begin;
// ============================================================
// BEGIN TEST
// ============================================================
function begin() {
    const nameInput =
        document.getElementById(
            'studentName'
        );
    const rollInput =
        document.getElementById(
            'rollNo'
        );
    studentName =
        nameInput
            ? nameInput.value.trim()
            : '';
    rollNo =
        rollInput
            ? rollInput.value.trim()
            : '';
    // --------------------------------------------------------
    // NAME REQUIRED
    // --------------------------------------------------------
    if (!studentName) {
        alert(
            'Please enter your name.'
        );
        if (nameInput) {
            nameInput.focus();
        }
        return;
    }
    // --------------------------------------------------------
    // RESET
    // --------------------------------------------------------
    idx = 0;
    answers = {};
    finished = false;
    seconds =
        test.minutes * 60;
    startTime =
        Date.now();
    // --------------------------------------------------------
    // RESET TIMER
    // --------------------------------------------------------
    clearInterval(
        timerId
    );
    timer.classList.remove(
        'urgent'
    );
    // --------------------------------------------------------
    // SHOW EXAM
    // --------------------------------------------------------
    start.classList.add(
        'hidden'
    );
    exam.classList.remove(
        'hidden'
    );
    // --------------------------------------------------------
    // RENDER
    // --------------------------------------------------------
    render();
    // --------------------------------------------------------
    // SHOW TIMER
    // --------------------------------------------------------
    updateTimer();
    // --------------------------------------------------------
    // START TIMER
    // --------------------------------------------------------
    timerId =
        setInterval(
            tick,
            1000
        );
}
// ============================================================
// UPDATE TIMER
// ============================================================
function updateTimer() {
    if (seconds < 0) {
        seconds = 0;
    }
    timer.textContent =
        fmt(seconds);
    if (seconds <= 60) {
        timer.classList.add(
            'urgent'
        );
    }
}
// ============================================================
// TIMER TICK
// ============================================================
function tick() {
    if (finished) {
        return;
    }
    seconds--;
    updateTimer();
    if (seconds <= 0) {
        seconds = 0;
        updateTimer();
        clearInterval(
            timerId
        );
        finish(true);
    }
}
// ============================================================
// RENDER QUESTION
// ============================================================
function render() {
    const q =
        test.questions[idx];
    if (!q) {
        return;
    }
    // --------------------------------------------------------
    // PROGRESS
    // --------------------------------------------------------
    progress.textContent =
        'Question ' +
        (idx + 1) +
        ' of ' +
        test.questions.length;
    // --------------------------------------------------------
    // ANSWERED COUNT
    // --------------------------------------------------------
    answeredCount.textContent =
        Object.keys(
            answers
        ).length +
        ' answered';
    // --------------------------------------------------------
    // QUESTION
    // --------------------------------------------------------
    question.innerHTML =
        '<h2>' +
        esc(
            q.question
        ) +
        '</h2>' +
        Object.entries(
            q.options || {}
        )
        .map(
            function ([key, value]) {
                const selected =
                    answers[q.id] === key
                        ? ' selected'
                        : '';
                return (
                    '<button ' +
                    'type="button" ' +
                    'class="option' +
                    selected +
                    '" ' +
                    'data-option="' +
                    esc(key) +
                    '">' +
                    '<b>' +
                    esc(key) +
                    ')</b> ' +
                    esc(value) +
                    '</button>'
                );
            }
        )
        .join('');
    // --------------------------------------------------------
    // OPTION BUTTONS
    // --------------------------------------------------------
    question
        .querySelectorAll(
            '.option'
        )
        .forEach(
            function (button) {
                button.onclick =
                    function () {
                        if (finished) {
                            return;
                        }
                        answers[q.id] =
                            button.dataset.option;
                        render();
                    };
            }
        );
    // --------------------------------------------------------
    // PREVIOUS
    // --------------------------------------------------------
    prevBtn.disabled =
        idx === 0;
    // --------------------------------------------------------
    // NEXT
    // --------------------------------------------------------
    nextBtn.disabled =
        idx ===
        test.questions.length - 1;
    // --------------------------------------------------------
    // QUESTION NUMBERS
    // --------------------------------------------------------
    numbers.innerHTML =
        test.questions
            .map(
                function (item, n) {
                    const answered =
                        answers[item.id]
                            ? 'answered '
                            : '';
                    const current =
                        n === idx
                            ? 'current'
                            : '';
                    return (
                        '<button ' +
                        'type="button" ' +
                        'class="qnum ' +
                        answered +
                        current +
                        '">' +
                        (n + 1) +
                        '</button>'
                    );
                }
            )
            .join('');
    // --------------------------------------------------------
    // QUESTION NUMBER NAVIGATION
    // --------------------------------------------------------
    numbers
        .querySelectorAll(
            '.qnum'
        )
        .forEach(
            function (button, n) {
                button.onclick =
                    function () {
                        if (finished) {
                            return;
                        }
                        idx = n;
                        render();
                    };
            }
        );
}
// ============================================================
// PREVIOUS BUTTON
// ============================================================
prevBtn.onclick =
    function () {
        if (
            !finished &&
            idx > 0
        ) {
            idx--;
            render();
        }
    };
// ============================================================
// NEXT BUTTON
// ============================================================
nextBtn.onclick =
    function () {
        if (
            !finished &&
            idx <
            test.questions.length - 1
        ) {
            idx++;
            render();
        }
    };
// ============================================================
// SUBMIT BUTTON
// ============================================================
submitBtn.onclick =
    function () {
        finish(false);
    };
// ============================================================
// FINISH TEST
// ============================================================
function finish(auto) {
    // --------------------------------------------------------
    // PREVENT DOUBLE SUBMISSION
    // --------------------------------------------------------
    if (finished) {
        return;
    }
    // --------------------------------------------------------
    // SAFETY CHECK
    // --------------------------------------------------------
    if (
        !test ||
        !Array.isArray(
            test.questions
        )
    ) {
        return;
    }
    // --------------------------------------------------------
    // MANUAL CONFIRMATION
    // --------------------------------------------------------
    if (!auto) {
        const confirmed =
            confirm(
                'Are you sure you want to submit the test?'
            );
        if (!confirmed) {
            return;
        }
    }
    // --------------------------------------------------------
    // MARK FINISHED
    // --------------------------------------------------------
    finished = true;
    // --------------------------------------------------------
    // STOP TIMER
    // --------------------------------------------------------
    clearInterval(
        timerId
    );
    // --------------------------------------------------------
    // CORRECT
    // --------------------------------------------------------
    let correct = 0;
    test.questions.forEach(
        function (q) {
            if (
                answers[q.id] ===
                q.answer
            ) {
                correct++;
            }
        }
    );
    // --------------------------------------------------------
    // ATTEMPTED
    // --------------------------------------------------------
    const attempted =
        Object.keys(
            answers
        ).length;
    // --------------------------------------------------------
    // WRONG
    // --------------------------------------------------------
    let wrong = 0;
    Object.keys(
        answers
    ).forEach(
        function (id) {
            const q =
                test.questions.find(
                    function (item) {
                        return (
                            String(
                                item.id
                            ) ===
                            String(id)
                        );
                    }
                );
            if (
                q &&
                answers[id] !==
                q.answer
            ) {
                wrong++;
            }
        }
    );
    // --------------------------------------------------------
    // UNANSWERED
    // --------------------------------------------------------
    const unanswered =
        Math.max(
            0,
            test.questions.length -
            attempted
        );
    // --------------------------------------------------------
    // PERCENTAGE
    // --------------------------------------------------------
    const percent =
        test.questions.length > 0
            ? Math.round(
                (
                    correct /
                    test.questions.length
                ) * 100
            )
            : 0;
    // --------------------------------------------------------
    // TIME TAKEN
    // --------------------------------------------------------
    const timeTaken =
        Math.max(
            0,
            Math.round(
                (
                    Date.now() -
                    startTime
                ) / 1000
            )
        );
    // --------------------------------------------------------
    // RESULT
    // --------------------------------------------------------
    const result = {
        title:
            test.title || 'Mock Test',
        name:
            studentName,
        roll:
            rollNo,
        total:
            test.questions.length,
        attempted:
            attempted,
        correct:
            correct,
        wrong:
            wrong,
        unanswered:
            unanswered,
        percent:
            percent,
        timeTaken:
            timeTaken,
        answers:
            answers,
        questions:
            test.questions,
        autoSubmitted:
            auto
    };
    // --------------------------------------------------------
    // SAVE RESULT
    // --------------------------------------------------------
    try {
        sessionStorage.setItem(
            'mockResult',
            JSON.stringify(
                result
            )
        );
    } catch (error) {
        console.error(
            'Result save error:',
            error
        );
        alert(
            'Unable to save your result.'
        );
        finished = false;
        return;
    }
    // --------------------------------------------------------
    // RESULT PAGE
    // --------------------------------------------------------
    window.location.href =
        'result.html';
}
// ============================================================
// INITIALIZE
// ============================================================
init();
